### ISSUE TITLE
incremental load files

### ISSUE THREAD

**Issue by gadget114514** [yasl-lang/yasl#104]
multiple yasl source files can be load incrementally.

**Comment by CoffeeTableEspresso** [comment]
What would this look like for users of YASL?

**Comment by CoffeeTableEspresso** [comment]
I was planning on adding a module system eventually (as in, a way to import YASL files from other YASL files), not sure what you have in mind here

**Comment by gadget114514** [comment]
Hi. as you said, importing file and string is what i expected, i guess. "require" in ruby, "import" in python.
"dofile", "dostring" in lua.

behavior and use case is 
1. at first, bootstrap script is loaded
2. next step, when script calls "loading other script" API, then on the fly compilation is executed, 
user can call function in the other bigger script.

bootstrap script like the following
---
load("foo.yasl"); //  file or string
foo();  // <- foo function is defined in foo.yasl, if foo.yasl cannot be loaded, foo is not found.
---  
it looks like dynamic loading.

**Comment by CoffeeTableEspresso** [comment]
Yea, I was planning on adding something like this eventually. I've detailed my plan here: https://github.com/yasl-lang/yasl-enhancements/blob/master/modules.md

Were you planning on working on this or was this just a feature request for me?

**Comment by gadget114514** [comment]
no, i'm looking forward to.
