### ISSUE TITLE
Add automated testing for other compilers

### ISSUE THREAD

**Issue by CoffeeTableEspresso** [yasl-lang/yasl#105]
In particular, I'd like to test that this compiles with MSVC.

I'd like to verify it compiles on Linux (clang / gcc), macOS (clang / gcc), Windows (MSVC).

Ideally, the automated tests could be run on all platforms as well, but even simply checking that it compiles on all platforms properly would be a start, as until very recently YASL wouldn't even compile with MSVC.

**Comment by NoLongerBreathedIn** [comment]
(It compiles fine with GCC 8.2.1 as either C or C++ on Fedora.)

**Comment by CoffeeTableEspresso** [comment]
Yup, same on Ubuntu. The idea of this ticket is that I only run automated tests on Linux using clang / gcc. I need to add C++ tests and tests for windows.

**Comment by CoffeeTableEspresso** [comment]
I've added support for this starting from v0.5.0
