### ISSUE TITLE
compiler crash when compiling many functions

### ISSUE THREAD

**Issue by gadget114514** [yasl-lang/yasl#126]
on v0.3.7, the following procedure produces SIGSEGV.
test programs in attached a.zip contains many function definitions and if statement.
ok.yasl exits without trouble.ng.yasl causes SIGSEGV. 
the number of function definition is very sensitive.
there looks threshold.
when i remove any function from ng.yasl, the result becomes ok. 

```
$ unzip a.zip
$ ./YASL ok.yasl
$ ./YASL ng.yasl
Segmentation fault (core dumped)
$ diff ok.yasl ng.yasl
4a5,6
> fn k73() {
> }
```

Attached file is here

[a.zip](https://github.com/yasl-lang/yasl/files/2880828/a.zip)

**Comment by CoffeeTableEspresso** [comment]
The YASL interpreter currently only supports 256 global variables, after which it will start overwriting old values.  `ng.yasl` has 259 global variables, `ok.yasl` has 258 (the first 2 are for the `io` and the `math` library, which get overwritten by but aren't used (so they don't cause an error). 

I'll extend the allowed number of globals to fix this problem.

**Comment by CoffeeTableEspresso** [comment]
Alright, this will now cause an error instead of breaking everything. (On 0.3.7 branch). I plan on allowing unlimited globals in the future as described here https://github.com/yasl-lang/yasl/issues/132.
