### ISSUE TITLE
make it compile as a C++ program

### ISSUE THREAD

**Issue by CoffeeTableEspresso** [yasl-lang/yasl#129]
currently uses some C-isms, but minor changes should make this compile with a C++ compiler too.

**Comment by NoLongerBreathedIn** [comment]
Can I try this?

**Comment by CoffeeTableEspresso** [comment]
Yes feel free to give this a try.
 
The big issue right now is `void *` casts and a few other type errors because C++ is stricter than C with these. Other than that, most of it should be fine as I've tried to avoid most  C specific stuff. 

One C specific feature I have used is flexible array members. These are offered as an extension to C++ on gcc and clang (i believe) so it's fine for now if they are still used.

You can work off of the v0.4.3 branch and do a PR to that branch once it's done.

**Comment by NoLongerBreathedIn** [comment]
Perhaps should be closed?

**Comment by CoffeeTableEspresso** [comment]
I'll close this once I've finished the tests for this, I haven't forgotten the issue.

**Comment by CoffeeTableEspresso** [comment]
I'm gonna close this an open another for the testing acrtually.
