### ISSUE TITLE
Feature suggestion: Add `record` type

### ISSUE THREAD

**Issue by chack05** [yasl-lang/yasl#154]
A record type in which no additional fields can be created at runtime. Having this additionally to dictionaries/tables brings the following advantages:

- Easier to read intended usage.
- Easier to debug, as you get errors instead of a table just adding another KV pair.
- In case of someone wanting to create a JIT compiler it's likely easier and less costly to trace and internally replace with an array.

There are at least two possible options on what this could look like (let's ignore the syntax for now):

a) Anonymous types:

```
# The record keyword is probably not the least error prone syntax.
myRecord := record {fieldA : 42, fieldB : "Bla"}

# This is ok.
myRecord.fieldA = 23
someVar := myRecord.fieldB
# This is not.
myRecord.fieldC = 72
```

b) Declared types:

```
record MyRecord {
    fieldA,
    fieldB = "defaultValue"
}

# This would allow omitting fieldB.
myRecord := MyRecord {fieldA : 42, fieldB : "Bla"}
```

This second form allows for checking if a type exists and if all required fields are filled.

Costs/Challenges:

- Making them easy to distinguish from tables (if you want to add them and maybe even sets and tuples it's not too late for a keyword-driven, unified initializer expression syntax, like list(...), table(...), ...)
- FFI/API interaction
- If YASL is all statements, in case of b) you'd need some annoying stuff like type hoisting or forward declaration, similar to with mutual recursion.

Related: Tuples

**Comment by CoffeeTableEspresso** [comment]
This would likely be a useful feature, but there's some work that needs to be done to decide the exact semantics and syntax.

Regarding your comments:
> In case of someone wanting to create a JIT compiler it's likely easier and less costly to trace and internally replace with an array.
I do plan on eventually writing a JIT compiler for YASL (once it's stable and I've finished writing all the features I need), so this would be useful. I am cautious about adding features just to help with JIT though.

A feature I plan to add to YASL is the ability to replace the metatable of a given object with a new one (the "metatable" is where any lookups of fields (including methods) are done).  Once this is added, the "anonymous types" version of your proposal could be implemented just by using a version of `__set` and `__get` (`__set` is called when you write something like `x.y = z` or `x[a] = z`, similar for `__get`) that doesn't allow you to add new fields.

> if you want to add them and maybe even sets and tuples it's not too late for a keyword-driven, unified initializer expression syntax, like list(...), table(...), ...
I am currently adding sets to YASL (partial implementation is on the v0.5.2 branch right now, still working on it). I plan on adding a few more useful data structures to YASL (possibly tuples, undecided at this point). I originally used `table(...)` and `list(...)`, but really missed the more compact `{ ... }` and `[ ... ]` syntax from Python, so I changed YASL to use that. All other data types in YASL will use a `set(...)` style syntax, though.

> FFI/API interaction
(Presumably you mean the C API.) Not sure about the interaction with the C API at this point, but it should be possible to come up with something reasonable for that, so I'm not too concerned.

>  If YASL is all statements, in case of b) you'd need some annoying stuff like type hoisting or forward declaration, similar to with mutual recursion.
YASL is statement based, but this shouldn't be an issue except with mutually recursive types.
