### ISSUE TITLE
'Expected _ got _' errors on for-loop

### ISSUE THREAD

**Issue by ryco117** [yasl-lang/yasl#172]
Using the two statements `let x = [] ; for let i = 0; i < 5; i++ { x->push('*') }` in either the REPL or source file for version v0.5.2, the following errors are returned:
```
SyntaxError: Expected :, got }, in line 1
SyntaxError: Invalid expression in line 2 (;).
SyntaxError: Expected }, got ;, in line 2
SyntaxError: Expected {, got ;, in line 2
SyntaxError: Invalid expression in line 2 (;).
SyntaxError: Expected }, got END OF FILE, in line 2
SyntaxError: Expected ;, got END OF FILE, in line 2
```

**Comment by CoffeeTableEspresso** [comment]
not a bug, but a very unclear syntax error message. I'll work on improving these in the future.
`++` is not legal in YASL, it's `+=1`. When YASL saw `i++`, it read it as `i + +{ ... }` (`i`, binary `+`, unary `+`, dict literal.
