### ISSUE TITLE
remove perl/bash dependency in most tests

### ISSUE THREAD

**Issue by CoffeeTableEspresso** [yasl-lang/yasl#174]
this will let the test suite be more portable. In particular, this will let us test the install on Windows.

**Comment by NoLongerBreathedIn** [comment]
Mind if I take this?

**Comment by CoffeeTableEspresso** [comment]
@NoLongerBreathedIn Feel free to take this!

If you only manage to get some working with C, or only manage to get rid of the perl dependency, that's fine too. I imagine the valgrind ones in particular might be a pain.

just do a PR to master once you have something and I can take a look.
