### ISSUE TITLE
Setting undef as key in table Double free

### ISSUE THREAD

**Issue by ryco117** [yasl-lang/yasl#220]
Discovered that setting the undef key in a table causes unexpected results on printing.
```
yasl> let a = {}
yasl> a[undef] = 5
yasl> echo a

yasl> let z = 9
double free or corruption (out)
Aborted (core dumped)
```

Any line can replace `yasl> let z = 9`, it will result in the same error.

NOTE: this error does not occur if there is something else in the table besides the undef key

**Comment by CoffeeTableEspresso** [comment]
merged into v0.6.3
