### ISSUE TITLE
io.read only takes first line

### ISSUE THREAD

**Issue by ryco117** [yasl-lang/yasl#236]
Using io.read on a file with multiple lines results in a string containing only the first line. Branch v.0.6.5

**Comment by CoffeeTableEspresso** [comment]
Not bug, just a shitty API. `io.read` takes two arguments: the file, and the mode. The mode can be `'l'` or `'a'` (for "line" or "all"), defaulting to `'l'` (hence reading a single line). Use `io.read(filename, 'a')` to read the whole file.

This will probably be changed in the next set of breaking changes.
