### ISSUE TITLE
add `list.insert` function to add elements at an arbitrary index of `list`

### ISSUE THREAD

**Issue by CoffeeTableEspresso** [yasl-lang/yasl#360]
`list->insert(index, value)` should add a new element `value` to `list` at index `index`, or cause an error if the `index` is out of bounds.

**Comment by DarthUdp** [comment]
I have a good idea of how I would go about implementing this one on a logic level but if you can describe what needs doing relative to this codebase it would be great

**Comment by CoffeeTableEspresso** [comment]
So, list methods are defined in `interpreter/list_methods.c`, you'll see examples for all the existing ones that should be what you need.

Methods are registered for the appropriate type in `interpreter/builtins.c`; There's a function `list_builtins` that handles lists.

In `specialstrings.x`:
- Add an entry for `insert`: `X(S_INSERT, "insert")`. (I use X-macros in a few places in YASL, let me know if you're not familiar with the technique.)

In `interpreter/list_methods.h`:
- Add a declaration `int list_insert(struct YASL_State *S);`

In `interpreter/builtins.c`:
- Add `table_insert_specialstring_cfunction(vm, table, S_INSERT, &list_insert, 3);` to `list_builtins`. (`S_INSERT` is the name, `list_insert` is the function you'll create, `3` is how many parameters you expect (including the list itself.))

In `interpreter/list_methods.c`:
- Implement `list_insert`. Hopefully the other functions in this file are enough to go off of, but let me know if you run into any trouble. 
- One thing to note when implementing is `list_insert` should specifically cause a `YASL_VALUE_ERROR` if the index is out of range.

(Optional):
- Add tests for this. If you don't want to no worries, I can do this for you, I know writing tests isn't exactly fun.

**Comment by DarthUdp** [comment]
looks good to me I will have a go at it

**Comment by DarthUdp** [comment]
One question what behavior do you expect? Insert and shift all indexes after by +1, or replace at index. I imagine the former is the desired behavior but never hurts to ask

**Comment by DarthUdp** [comment]
I'm going to copy the API of `list___set` for consistency if you don't mind

**Comment by CoffeeTableEspresso** [comment]
Insert and shift indices after by +1. Just replacing at index can already be done by `ls[index] = value`.

**Comment by DarthUdp** [comment]
another question should I mutate the list or return a new copy functional style?

**Comment by CoffeeTableEspresso** [comment]
Mutate the list, most/all of the existing list functions do this.

**Comment by DarthUdp** [comment]
I have a first prototype ready

**Comment by CoffeeTableEspresso** [comment]
Done on v0.11.3
