### ISSUE TITLE
Add way to call functions from C API

### ISSUE THREAD

**Issue by CoffeeTableEspresso** [yasl-lang/yasl#361]

**Comment by DarthUdp** [comment]
this one and #336 are my main blockers to try yasl in a project I have in mind

**Comment by CoffeeTableEspresso** [comment]
Well, always happy to have people trying out YASL, I'm happy to work on these next chance I get so I can unblock you!

This issue should be pretty straightforward, other one is a bit more work but I know roughly what I want to do there too.

And, do let me know if there's anything else missing that you'd like added as well.

**Comment by CoffeeTableEspresso** [comment]
On v0.11.3 branch now
