### ISSUE TITLE
add function to seed random numbers

### ISSUE THREAD

**Issue by CoffeeTableEspresso** [yasl-lang/yasl#376]
we have `math.rand()` for generating numbers, but no way to seed them unfortunately.

**Comment by DarthUdp** [comment]
Hey, I would like to try at this one, what do you have in mind for seeding? use OS provided randomness, or assembly instructions but that opens the ISA can of worms.

**Comment by CoffeeTableEspresso** [comment]
No need to anything hardware or OS specific, I was planning on just using the features built into the C standard library for this. Basically a nice wrapper for `srand` was what I had in mind.

**Comment by DarthUdp** [comment]
Hey, okay simpler than I had in mind then since I remember how to add a function to yasl I can give it a go I hope relatively quickly

**Comment by CoffeeTableEspresso** [comment]
Sounds good to me! This should probably go under the `math` library (alongside the existing functions that actually use the random seed).

**Comment by DarthUdp** [comment]
ok, I will give it a go today/tomorrow

**Comment by CoffeeTableEspresso** [comment]
Added in v0.11.12
