### ISSUE TITLE
`math.clamp`

### ISSUE THREAD

**Issue by CoffeeTableEspresso** [yasl-lang/yasl#405]

**Comment by RandyKdev** [comment]
Good day, @CoffeeTableEspresso, I would like to have a shot at this but it has no description. Please can a context be given for this?

**Comment by CoffeeTableEspresso** [comment]
Yup, sorry, I don't have too many contributors so I sometimes don't give the best descriptions.

The idea for `math.clamp` is:

`math.clamp(value, min, max)` returns `value` if `min <= value <= max`. If `value < min`, return `min`, and if `value > max` return `max`. (Basically, we're making sure we always return something between `min` and `max`, inclusive.)

As for implementing it, this should go into the `math` part of the standard library, which is found here: https://github.com/yasl-lang/yasl/blob/master/std/yasl-std-math.c

There's two pieces: Write the function, and register it (at the bottom of the file mentioned). Most of the functions in that file should show you what you need to do.

Once you've done that, the function itself should be callable from a YASL script using `math.clamp(a, b, c)`.

If you write tests that would be good, but I understand it's not very fun so you can leave those to me if you'd like.

Hopefully that's enough to get you started, let me know if you have any questions or need any help.

**Comment by RandyKdev** [comment]
Ok thanks @CoffeeTableEspresso 

I am a first-time contributor here and it might take me sometime to get everything going.

**Comment by RandyKdev** [comment]
Please, some clarification needed

Should the `math.clamp` function push different data types, per the data types of its parameters, to the top of the stack?
For example, from the function definition `math.clamp(value, min, max)`, are the examples below correct

- `math.clamp(34, 35.5, 100)` == 35.5 ?
- `math.clamp(150.0, 35.5, 100.5)` == 100.5 ?
- `math.clamp(34.1, 0, 100)` == 34.1 ?
- `math.clamp(34, 0, 100)` == 34 ?

Thanks.

**Comment by CoffeeTableEspresso** [comment]
Yes, it would be best to preserve the existing numeric types. All the examples listed are correct.

**Comment by RandyKdev** [comment]
Ok.

**Comment by CoffeeTableEspresso** [comment]
Added to v0.11.8
