### ISSUE TITLE
Efficiency gain by having `YASL_peekcstr()` return the managed reference (possibly `const`)

### ISSUE THREAD

**Issue by ryco117** [yasl-lang/yasl#473]
The current implementation/API of `YASL_peekcstr()` looks at the object on top of the stack and if it is a string, copies it to a new buffer and returns the new buffer pointer. However, since the operation specifies that it is peeking the stack data, could we safely get a more performant API by returning the C-string pointer itself? Then callers of this function (such as `YASL_popcstr()`) will need to allocate a buffer for the data if they want it, which popcstr would, but callers that are only interested in a read-only peak of the string get a more performant function call.

**Comment by CoffeeTableEspresso** [comment]
peekcstr unfortunately cannot, since the string may not be nul-terminated (due to the way strings are implemented in YASL).

However, I've added `YASL_peeknstr` in v0.13.3 which behaves like this (returning the string itself instead of copying it.
