### ISSUE TITLE
The '??' operator needs updating

### ISSUE THREAD

**Issue by ryco117** [yasl-lang/yasl#81]
The '??' operator does not have documentation and is giving the opposite argument from the expected. Eg. `echo undef ?? 'default'` prints `undef`

**Comment by CoffeeTableEspresso** [comment]
this is a bug, `??` should have the behaviour described in the examples.

**Comment by CoffeeTableEspresso** [comment]
This will be fixed in version 0.3.4

**Comment by CoffeeTableEspresso** [comment]
fixed in v0.3.4
