### ISSUE TITLE
Logical not before function name starting with "in"

### ISSUE THREAD

**Issue by ryco117** [yasl-lang/yasl#85]
Example code:
`fn inEpsilon(a, b) {
	return math.abs(a - b) < 10**-10
} `\
`
echo !inEpsilon(0, 0.1**5.0)
`
fails to parse. It appears to be the `!in` having priority over the function name that is causing the issue.

**Comment by CoffeeTableEspresso** [comment]
Yup this is definitely a bug. I'll look into it.

**Comment by CoffeeTableEspresso** [comment]
Having a quick glance around, a space after `!` should fix this temporarily.

**Comment by CoffeeTableEspresso** [comment]
Merged a fix for this into the v0.3.5 branch a while ago
