### ISSUE TITLE
input source from memory buffer

### ISSUE THREAD

**Issue by gadget114514** [yasl-lang/yasl#96]
On some platform, "FILE" is not supported.  Source on "stream" or "direct memory" should be alternatives.

**Comment by CoffeeTableEspresso** [comment]
This would probably require quite a bit of work since the lexer relies pretty heavily on FILE at the moment

**Comment by CoffeeTableEspresso** [comment]
What platforms are you specifically worried about?

**Comment by gadget114514** [comment]
I try to use this vm with cocos2d-x. 
i sent patches about this issue. plz review them.

**Comment by CoffeeTableEspresso** [comment]
Yea I'm looking at your patch now.

What problems specifically did you run into though? And on what platform specifically. I can't think of a platform that doesn't support `FILE *`.

Lastly, I really hope you're not trying to use this VM in production, as it's definitely not ready for that yet.

**Comment by CoffeeTableEspresso** [comment]
It looks good besides a few minor things which i mentioned on the review. Once those are fixed I'll merge this in. 

Thanks for the changes!

**Comment by CoffeeTableEspresso** [comment]
This mix has been merged into the v0.3.5 branch. Thanks again! This will also help with implementing a REPL later on, so double thanks!
